[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"
startCommand = "npm run preview"

[env]
NODE_VERSION = "20"

[deploy]
rootDirectory = "client"
startCommand = "npm start"



